<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -5 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-5' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ) )),
);